package modi;

public enum PeakProperty {
  NORMAL,
  N_TERM_B_ION_ONLY,
  N_TERM_Y_ION_ONLY,
  C_TERM_B_ION_ONLY,
  C_TERM_Y_ION_ONLY,
  Y_ION,
  Y_MINUS_NH3_ION,
  Y_MINUS_H2O_ION,
  B_ION,
  B_MINUS_NH3_ION,
  B_MINUS_H2O_ION,
  A_ION,
  DIAGNOSTIC_ION,
  DIAGNOSTIC_PTM_ION,
  VIRTUAL_PEAK,
  ISOTOPE,
}
